### ISSUE TITLE
Figure out how to make Sign Protocol attestation from mtDog

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/MonadicDNA#10]
For the Monadic DNA Portal and SnipperBot, Sign Protocol attestations aren't an issue because the code is written in Node.js. However, for mtDog, we decided to write the application fully in Rust. As a result, we can simply copy and adapt the attestation code from SnipperBot. 

There are two potential solutions:
1. Figure out a way to interact with Sign Protocol from Rust, potentially using their hosted service
2. Find a way to invoke a Node.js code snippet from Rust

The deliverable for this ticket is a Github snippet demonstrating a solution.

**Comment by vishakh** [comment]
On second thought, both approaches above are too much for a hackathon. Instead, here's what I suggest:
- [ ] Create a basic Express.js project in `mtDog/web` for a Sign Protocol API
- [ ] Create an HTTP POST route called `sign/VerifiedTrait` which takes the fields `passport_id`, `provider`, `trait` and `value` to create a new VerifiedTrait attestation on Sign Protcol and then return the ID of the attestation to the caller. You can look at https://github.com/Cryptonomic/MonadicDNA/blob/main/monadic-dna-portal/src/utils/attestations.ts for the Sign Protocol code. 
- [ ] Once the Rust UI is ready, add code to it to invoke this service to make attestation. 

@bhaskarkishore Let us know here if you have any objections.

**Comment by amardeepio** [comment]
https://github.com/Cryptonomic/MonadicDNA/pull/14/files#diff-2a1592a27896c89365f9281699d0480e13697cab246bc6b7f52584e847bd69e2

**Comment by vishakh** [comment]
Closed by #14.
