### ISSUE TITLE
Create intial Data Manager service

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/MonadicDNA#2]
The Data Manager service
- Implements a REST API
- Given a large file, breaks it up into small chunks and puts them on long term storage (via Lighthouse). Respond with a JSON file containing the provided file name and the IDs of the each chunk.
- Given a chunk ID, fetches the given chunk from long term storage and returns it to the caller

Action items:
- [ ] Create a REST API in `services/data-manager`
- [ ] An HTTP PUT call at `payloads/{passport-id}` should split the given 23andMe file into chunks, store the chunks on external storage and then return a JSON file containing the passport ID and the external storage IDs of each chunk.
- [ ] An HTTP GET call at `chunks/{chunk-id}` should return the requested chunk. 

@bhaskarkishore Please review the above.

**Comment by amardeepio** [comment]
lighthouse generate CID so can we use that as passport ID ?

**Comment by vishakh** [comment]
Based on changes to the project scope, we no longer need a Data Manager. 

See #5 for data processing functionality for Nillion.
