### ISSUE TITLE
Monadic DNA UI Review 

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/MonadicDNA#28]
- [x] Monadic DNA Logo is blurry. Here are svgs of the logo

![MonadicDNA_Logo](https://github.com/Cryptonomic/MonadicDNA/assets/60450742/115a487d-e925-4a84-91d8-c06709b89e6e)

![Vector (3)](https://github.com/Cryptonomic/MonadicDNA/assets/60450742/3a5a8c38-aab1-4813-b254-914780846307)
--------
- [ ] On the bottom of every landing page, “get in touch” should link to on of our social pages (website or twitter) or open an email client with info@cryptonomic
- [x] On the “create DNA Passport” tab remove the ‘Max x GB” because we don’t have a file size limit
- [x] Change the text on the upload component to “23andMe genetic data .txt file” instead of the “Exome sequencing or genotyping data”

**Comment by vishakh** [comment]
Closed by multiple PRs.
