### ISSUE TITLE
Create initial Monadic DNA portal

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/MonadicDNA#3]
The initial version of the Monadic DNA portal should do the following:
- [ ] Create a basic UI scaffold based on your understanding of the component. 
- [ ] Return a JSON file representing a [DNA Passport](https://discourse.cryptonomic.tech/t/dna-passport-for-monadic-dna/449) with a passport ID (MD5 hash of the given filename), the MD5 hash of the file and a map of the SNPs and store IDs returned by the Nillion service. 
- [ ] Create a PR with the above. 
- [ ] During DNA wallet creation, perform an attestation on Sign Protocol using [our shared account ](https://discourse.cryptonomic.tech/t/team-account-for-scaling-ethereum-2024/456) as the signer.
- [ ] Add functionality to let the user upload their DNA wallet to see all the Sign Protocol attestation they have received. 
- [ ] Create a PR with the above.
- [ ] Implement the design specified by @navi-arneja 
- [ ] Create a PR with the above

**Comment by vishakh** [comment]
Some additional items:
- [ ] Come up with a schema for Sign Protocol for attesting that a given passport ID is valid, along with all the other information in the DNA passport. Add the schema to a `schemas` directory in the root of the repo.
- [ ] When a DNA passport is being generated, perform an attestation on Sign Protocol using the above schema using [our shared account ](https://discourse.cryptonomic.tech/t/team-account-for-scaling-ethereum-2024/456)as the signer.

**Comment by vishakh** [comment]
Updated the ticket to reflect recent Nillion work.

**Comment by vishakh** [comment]
There is a shared Nillion Interactor instance running now so you don't have to run it locally.

The details can be found at https://discourse.cryptonomic.tech/t/infrastructure-for-scaling-ethereum-2024/457/2?u=vishakh. 

The service is pretty brittle because the Nillion node is brittle. Any actions may have to be retried up to five times to get a valid return value.

**Comment by vishakh** [comment]
Here's an LLM-generated snippet which shows how to call the `dataset` route:

```javascript
import axios from 'axios';
import { useState } from 'react';

function UploadForm() {
    const [file, setFile] = useState(null);

    const onFileChange = event => {
        setFile(event.target.files[0]);
    };

    const onFileUpload = async () => {
        const formData = new FormData();
        formData.append("file", file);
        
        try {
            const response = await axios.put("http://localhost:5000/dataset", formData, {
                headers: {
                    'Content-Type': 'multipart/form-data'
                }
            });
            console.log('Server response:', response.data);
        } catch (error) {
            console.error('Error uploading file:', error);
        }
    };

    return (
        <div>
            <input type="file" onChange={onFileChange} />
            <button onClick={onFileUpload}>
                Upload!
            </button>
        </div>
    );
}

export default UploadForm;
```

**Comment by vishakh** [comment]
> Some additional items:
> 
> * [ ]  Come up with a schema for Sign Protocol for attesting that a given passport ID is valid, along with all the other information in the DNA passport. Add the schema to a `schemas` directory in the root of the repo.
> * [ ]  When a DNA passport is being generated, perform an attestation on Sign Protocol using the above schema using [our shared account ](https://discourse.cryptonomic.tech/t/team-account-for-scaling-ethereum-2024/456)as the signer.

Some Sign Protocol schemas we can use:
- [MonadicDNA-ValidDataset](https://testnet-scan.sign.global/schema/onchain_evm_84532_0x4e)
- [MonadicDNA-VerifiedTrait](https://testnet-scan.sign.global/schema/onchain_evm_84532_0x4f)
- [MonadicDNA-VerifiedProvider](https://testnet-scan.sign.global/schema/onchain_evm_84532_0x50)

@Aeesh One thing to keep in mind is that the attestations should be done by the app in the background and not the user, i.e. the user should not have to use MetaMask in any way or be aware that any blockchain interactions are even involved in the apps. 

If you look at https://docs.sign.global/developer-apis/index-1/npm-sdk, you will see that a private key can be specified (use our shared hackathon account) to prevent Metamask from popping up:

```javascript
const privateKey = '0xabc'; // optional

const client = new SignProtocolClient(SpMode.OnChain, {
  chain: EvmChains.polygonMumbai,
  account: privateKeyToAccount(privateKey), // Optional,if you want to use the browser plugin account does not need to pass in
});

// ..

// create attestation
const createAttestationRes = await client.createAttestation({
  schemaId: '0x3',
  data: { name: 'a' },
  indexingValue: 'xxx',
});

```

**Comment by vishakh** [comment]
My proposal for the DNA Wallet format:

```json
{
	"passport_id": "monadicdna_d4ebe4575e8f7424675b2b649c187130",
	"filename_hash" "d4ebe4575e8f7424675b2b649c187130",
	"data_hash": "c883c31de259a072a8b5199c72b936cd",
	"nillion_data":
		{
		  "rs10811661": "5d4448fb-60e9-4fda-8020-da006f405acd",
		  "rs1111875": "570f77a1-9e33-439d-8f4c-a0ce2e7e2d94",
		  "rs13266634": "0bf13aae-4d72-47a3-baef-2f07fb27e890",
		  "rs1801282": "1dcf1018-f6d9-4ebc-b435-8df3dca78707",
		  "rs1815739": "ea64a530-1f64-49e5-8d9c-f57d16674a55",
		  "rs4402960": "3bdda1dd-7aac-448b-9219-618047fb54e9",
		  "rs5219": "d53aaa3d-09a8-43c7-8c49-316009b38284",
		  "rs6025": "87253aa0-d93b-4897-aad2-689c270134e1",
		  "rs7754840": "64ba9f63-d4a7-4c73-974e-484afae70486",
		  "rs7903146": "87b8ced5-81eb-4879-9e2d-601dfbad411a",
		  "rs8050136": "060a0fd1-acc4-422e-9ca0-d1797f14e4e1",
		  "rs9300039": "b9c46899-68b7-4bf0-bbf8-4fd6c3e6b070"
		}

}
```

Here is how I generated the hashes:

```
(base) vishakh@vishakhs-super-pc:~/dev/cryptonomic/MonadicDNA/services/nillion-interactor$ md5sum testdata/hu278AF5_20210124151934.txt 
c883c31de259a072a8b5199c72b936cd  testdata/hu278AF5_20210124151934.txt


) vishakh@vishakhs-super-pc:~/dev/cryptonomic/MonadicDNA/services/nillion-interactor$ echo "hu278AF5_20210124151934.txt" | md5sum
d4ebe4575e8f7424675b2b649c187130  -
```

An NPM library should be able to do the same kind of hashing.

**Comment by Aeesh** [comment]
> > Some additional items:
> > 
> > * [ ]   Come up with a schema for Sign Protocol for attesting that a given passport ID is valid, along with all the other information in the DNA passport. Add the schema to a `schemas` directory in the root of the repo.
> > * [ ]   When a DNA passport is being generated, perform an attestation on Sign Protocol using the above schema using [our shared account ](https://discourse.cryptonomic.tech/t/team-account-for-scaling-ethereum-2024/456)as the signer.
> 
> Some Sign Protocol schemas we can use:
> 
> * [MonadicDNA-ValidDataset](https://testnet-scan.sign.global/schema/onchain_evm_84532_0x4e)
> * [MonadicDNA-VerifiedTrait](https://testnet-scan.sign.global/schema/onchain_evm_84532_0x4f)
> * [MonadicDNA-VerifiedProvider](https://testnet-scan.sign.global/schema/onchain_evm_84532_0x50)
> 
> @Aeesh One thing to keep in mind is that the attestations should be done by the app in the background and not the user, i.e. the user should not have to use MetaMask in any way or be aware that any blockchain interactions are even involved in the apps.
> 
> If you look at https://docs.sign.global/developer-apis/index-1/npm-sdk, you will see that a private key can be specified (use our shared hackathon account) to prevent Metamask from popping up:
> 
> ```js
> const privateKey = '0xabc'; // optional
> 
> const client = new SignProtocolClient(SpMode.OnChain, {
>   chain: EvmChains.polygonMumbai,
>   account: privateKeyToAccount(privateKey), // Optional,if you want to use the browser plugin account does not need to pass in
> });
> 
> // ..
> 
> // create attestation
> const createAttestationRes = await client.createAttestation({
>   schemaId: '0x3',
>   data: { name: 'a' },
>   indexingValue: 'xxx',
> });
> ```
> 
> Remember, we are working not on Polygon Mumbai but on Base Sepolia.
> 
> The issue description has also been updated.

Ah okay, I am going to make that change locally to avoid the user interacting with the wallet.
