### ISSUE TITLE
Create initial mtDog library

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/MonadicDNA#4]
- [x] Read and understand the RISC Zero docs
- [x] Initialize a new RISC Zero project at `mtDog/lib`
- [x] Write code to load a 23andMe file and look for https://www.snpedia.com/index.php/Rs4988235 in it
- [x] Create a PR for the team's review

**Comment by vishakh** [comment]
Additional task:

Implement the following algorithm:
- Look for the ten SNPs on https://www.snpedia.com/index.php/Type-2_diabetes
- For each SNP, if the genotype corresponds to higher risk, add 1 to the risk score:
- Return the risk score at the end

**Comment by amardeepio** [comment]
https://github.com/Cryptonomic/MonadicDNA/pull/7

**Comment by vishakh** [comment]
Closed by #8.
