### ISSUE TITLE
Create snippet of code for RISC Zero verification

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/MonadicDNA#48]
Every attestation created by mtDog has a RISC receipt in its result. For example, https://testnet-scan.sign.global/attestation/onchain_evm_84532_0x14d contains this:

```json
{
  "pre": {
    "Value": {
      "pc": 2110468,
      "merkle_root": [
        1329308600,
        500664740,
        1359879458,
        4160867888,
        4104960824,
        3981007868,
        2318588229,
        3829733868
      ]
    }
  },
  "post": {
    "Value": {
      "pc": 2111716,
      "merkle_root": [
        1329308600,
        500664740,
        1359879458,
        4160867888,
        4104960824,
        3981007868,
        2318588229,
        3829733868
      ]
    }
  },
  "exit_code": {
    "Halted": 0
  },
  "input": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "output": {
    "Value": {
      "journal": {
        "Pruned": [
          2523312931,
          3873501960,
          392307065,
          3437878156,
          3218774505,
          3849554208,
          2809477828,
          2986745403
        ]
      },
      "assumptions": {
        "Value": []
      }
    }
  }
}
```

Ideally, we should include a verification of this result in our Monadic DNA Portal's results section. 

There is a verifier contract on Ethereum Sepolia: https://dev.risczero.com/api/blockchain-integration/contracts/verifier

Write a snippet of code which, maybe using web3.js or ethers.js, can verify the proofs we get from Risc Zero. 

If the snippet works and there is time, we can incorporate it into the portal.

**Comment by bhaskarkishore** [comment]
Just a note, that is only the claim part of the receipt. If other fields are required, let me know and i can modify mtDog to produce them.

**Comment by vishakh** [comment]
Out of scope for the hackathon due to time constraints. We can revisit this later.
